### ISSUE TITLE
Renderer: Irrlicht

### ISSUE THREAD

**Issue by billyquith** [billyquith/GWork#12]
Add Irrlicht renderer from: https://github.com/fengye/GWEN/commit/1b7d37b721172ad1699755d8ff3de90b6222fd02

**Comment by kklouzal** [comment]
@billyquith Might you please rethink adding the Irrlicht renderer to GWork? I know many members of the Irrlicht community who would use GWork. If not please add documentation on how users can create their own renderers for GWork specifically and I'll go ahead and create it and post a pull request! Thank you for your time.

**Comment by billyquith** [comment]
> I know many members of the Irrlicht community who would use GWork.

Ok, I'll consider it. Maintaining the renderers is work though. If the people that want to use it make a comment on this issue it will make it more likely to happen. I'd be interested to know what people want to use it for.

**Comment by kklouzal** [comment]
I'll pass the word around; My reasoning for creating the renderer in the first place and subsequently using it was because Irrlicht's built in GUI looks absolutely horrible and is missing many of the features provided by GWork/GWEN (I hate to say that because I love the engine). I'm also very proficient in the provided controls and can use it to make beautiful in-game menus.

Fortunately the renderer for Irrlicht should require very little to no upkeep at all once it's first created. The one I made here a few years ago should basically be copy paste.

Thank you again for your time and dedication to this project!

**Comment by billyquith** [comment]
You should be able to port the  GWEN version pretty easily. The project uses cmake instead of premake, is all UTF8, and had a resource loader. Most of the other renderer stuff is pretty similar.

From: http://irrlicht.sourceforge.net/forum/viewtopic.php?f=9&t=50017

> The unit-tests are perfect. I'm kinda stuck using garry's fork after spending two weeks binding 72 of the control classes into lua, 30,000 lines of code later I'm not going to switch :P I'm happy to hear though this has helped someone in a commercial application!

I'm also adding reflection to Gwork, using [Ponder](https://github.com/billyquith/ponder), and this will supply Lua bindings. Hopefully I'll find some time to push this out over Xmas.

**Comment by kklouzal** [comment]
I originally created the Irrlicht Renderer almost 4 years ago; Somewhere during that time I got rid of my GitHub repo and lost all the work I did. Fortunately my current project doesn't require lua bindings and don't think it ever will.

Reflection to lua with Ponder sounds interesting, I could see myself using it in the future, but not for every project. Hopefully it will be an optional flag users can tick in cmake. Keep up the good work!

**Comment by kklouzal** [comment]
I've got it working except for a color bug which I can't pin down. Tried a boat load of things to get the yellow color to change but with no luck..
https://i.imgur.com/8SwUuj2.png

You can see the current code in this commit.
https://github.com/kklouzal/GWork/commit/39515535c4bed141d0d60cc8bc80437fa6070582
I wasn't able to get the cmake script to properly generate the project files so at the moment you have to manually add your header/library paths to the project.

**Comment by kklouzal** [comment]
@billyquith do you have any idea why the yellow text and blocks are appearing? If I manually change the code in the following function to set the color to red it draws everything red so it seems like GWork is setting the color to yellow somewhere when it shouldn't or not changing the color somewhere it should?

```cpp
void Irrlicht::SetDrawColor(Gwk::Color color)
{
    DrawColor.set((irr::u32)color.a, (irr::u32)color.r, (irr::u32)color.g, (irr::u32)color.b);
}
```

**Comment by billyquith** [comment]
I think perhaps the get colour of pixel function is not working. It samples the skin to get a colour to be used.

**Comment by kklouzal** [comment]
There we go! I was still using the old naming scheme "Colour" I'm happy to see you changed it to "Color" :)
https://i.imgur.com/fK5csYE.png

**Comment by billyquith** [comment]
Done.
