### ISSUE TITLE
Fix Windows builds

### ISSUE THREAD

**Issue by billyquith** [billyquith/GWork#13]
I've been testing on Mac OSX. Cross platforms SDKs SFML2 and Allegro5 tested. Windows needs some work to refactor for the changes.

(edit) **Note: This issue is specific to the Windows APIs, i.e. DirectX**

**Comment by eXpl0it3r** [comment]
I could help you out a bit. Got the libraries to build, but am still having linker issues regarding the platform specific functions when trying to build the SFML example.

Let me know if you already have something in mind or code, so I don't waste my time reinventing the wheel. :wink:

**Comment by billyquith** [comment]
Hi, if you have errors could you please open a new issue, describe it, and paste in any error logs you get, otherwise it is too much guess work.

**Comment by billyquith** [comment]
I'm in no hurry to fix this as use cross platform libraries. If you require this working then by all means contribute a pull request.

**Comment by billyquith** [comment]
Did more work on this. Currently Windows builds use null platform. Direct2D runs but has glitches.

**Comment by billyquith** [comment]
DirectX9 deprecated. Add DirectX11 renderer? https://github.com/garrynewman/GWEN/commit/f58a76ee45ce957e50fdd3a72453c6e5211f6227
https://github.com/garrynewman/GWEN/pull/90

**Comment by billyquith** [comment]
I'm going to close this for now as Windows platform fixed and DirectX11 working.
