### ISSUE TITLE
Allegro keyboard input handling logic

### ISSUE THREAD

**Issue by Grant1219** [billyquith/GWork#24]
I have found a small bug when entering text, which sometimes causes modifier keys to input characters.

https://github.com/billyquith/GWork/blob/gwork/source/platform/include/Gwork/Input/Allegro5.h#L122-L123

I believe there should be some extra bounds checking done there before passing the character to InputCharacter, unless InputCharacter is not **only** for visible characters.

http://liballeg.org/a5docs/trunk/events.html#allegro_event_key_char

It seems like sometimes non-character keys can generate strange values for unichar. An example of this is on Mac OSX the command key inputs a "j" character in textboxes. I will look into fixing this, but let me know if I am missing a larger issue.

**Comment by billyquith** [comment]
Not sure why char is using Allegro unichar. Looks like it should use the keycode. 

``` cpp
case ALLEGRO_EVENT_KEY_CHAR:
    return m_eventListener->InputCharacter(event.keyboard.unichar);

case ALLEGRO_EVENT_KEY_DOWN:
case ALLEGRO_EVENT_KEY_UP:
    {
        bool bPressed = (event.type == ALLEGRO_EVENT_KEY_DOWN);

        if (event.keyboard.keycode
            && bPressed
            && event.keyboard.keycode >= 'a'
            && event.keyboard.keycode <= 'z')
        {
            return m_eventListener->InputCharacter(event.keyboard.keycode);
        }

        const unsigned char iKey = TranslateKeyCode(event.keyboard.keycode);
        return m_eventListener->InputKey(iKey, bPressed);
    }
```

**Comment by billyquith** [comment]
Might also be worth having a poke around in the GWEN issues list and PR history. GWEN has quite a few bugs.

**Comment by billyquith** [comment]
This should be fixed now.

**Comment by Grant1219** [comment]
You are awesome.
I have been moving and just had some time to come back and look at this, and it's already done!
