### ISSUE TITLE
Cross Platform Debug Break

### ISSUE THREAD

**Issue by eXpl0it3r** [billyquith/GWork#25]
While trying to get GWork running on Windows with a MinGW x64 compiler, I've run into a compiler issue with the [`_asm { int 3 }`](https://github.com/billyquith/GWork/blob/gwork/source/gwork/source/Utility.cpp#L325) code that is basically a break point. While looking for how to make this better and cross platform [I learned](https://github.com/scottt/debugbreak) that it's not exactly that easy. For our case we could for GCC (and clang?) we could go with `__builtin_trap()` and for MSVC use `__debugbreak()`. Or as an alternative we could use the [header file provided by Scott Tsai](https://github.com/scottt/debugbreak) which has been tested for many platforms and works around possible issues.

What do you think?

**Comment by billyquith** [comment]
Have you tested this with MinGW x64 compiler, and it works as expected?

**Comment by eXpl0it3r** [comment]
I've tested the debugbreak.h header and it works great.

![GDB](http://i.imgur.com/PfW1wsZ.png)

While the `__builtin_trap()` generates a SIGILL signal from which you can't just continue (I think).

![GDB](http://i.imgur.com/L8DXU2R.png)

**Comment by billyquith** [comment]
Done. Tested on OSX.
