### ISSUE TITLE
Integrate GWork into another project

### ISSUE THREAD

**Issue by ghost** [billyquith/GWork#35]
Is there any prefered mechanism for integrating GWork into a project? 

Merely setting it as a subproject using _add_subdirectory(GWork)_ doesn't seem to work, but there is also no provided _FindGWork.cmake_ to allow finding GWork externally. 

Any help appreciated!

**Comment by billyquith** [comment]
Hi, do you have any error output please? I think it probably doesn't work because Gwork thinks it is the root project when it isn't so the paths are wrong. Since this is an embeddable GUI it should work!

**Comment by billyquith** [comment]
It should be fixed now for embedding. See wiki for example Cmake config.

**Comment by ghost** [comment]
That worked!~
