### ISSUE TITLE
MinGW does support CODECVT

### ISSUE THREAD

**Issue by eXpl0it3r** [billyquith/GWork#37]
As mentioned in [my comment](https://github.com/billyquith/GWork/commit/0d9aca4afac81ae88c78c2e39ae23e1fbfb86b30#commitcomment-19266406) the following logic makes it that `AVOID_CPP11_CODECVT` is always set when using a MinGW compiler, even though MinGW also supports codecvt (probably starting from GCC 5.1 upwards as well).

``` cpp
#if ((defined(__GNUC__) && !(__GNUC__ >= 5 && __GNUC_MINOR__ > 1)) \
     || defined(__MINGW32__)) \
    && !defined(__APPLE__)
 #   define AVOID_CPP11_CODECVT
 #endif
```

The easy fix could be to just remove the `__MINGW32__` check since the GNUC check should work for MinGW as well.

Furthermore MinGW doesn't seem to support the `alloca.h` header, so when someone would be using an older compiler the else branch would fail to compile.

``` cpp
// Note: <codecvt> is C++11. It exists in libc++ (LLVM) but is patchy in libstdc++ pre-GCC 5
#ifndef AVOID_CPP11_CODECVT
#   include <codecvt>      // Narrow/widen - C++11
#else
#   include <iconv.h>
#   include <alloca.h>
#endif
```

[One fix I saw](https://github.com/ocornut/imgui/issues/276) is to use `malloc.h` for Windows.

Relevant file: https://github.com/billyquith/GWork/blob/gwork/source/gwork/source/Utility.cpp

On a personal note: I find the double "negation" a bit confusing. Why define a Marco called "AVOID_X" and the check whether it's NOT defined? But that's maybe just me. :wink:

**Comment by billyquith** [comment]
> On a personal note: I find the double "negation" a bit confusing. Why define a Marco called "AVOID_X" and the check whether it's NOT defined? But that's maybe just me.

I suppose it could be a value and inverted. You are free submit a patch. ;)

**Comment by billyquith** [comment]
Compile bugs should be fixed. If you want to make the define a value and test for `#if` then be my guest.
