### ISSUE TITLE
Fix a couple of warnings

### ISSUE THREAD

**Issue by ipo** [billyquith/GWork#40]
I had a couple of warnings when using GWork that annoyed me, so I fixed them.  I also made a non-const parameter const, minor change.  Maybe you want to merge this, maybe not.

It doesn't seem possible to create a pull-request from a repo outside of a straight github<->github fork, so here's the diff: https://gitlab.com/jonas.lindgren/gwork/commit/587b164541a9e057e7bea2e5b078324618e99194.diff

**Comment by eXpl0it3r** [comment]
Since you have an account here, you could also quickly fork the repository, add it as additional remote and push to here. :wink:

**Comment by billyquith** [comment]
Thanks for looking at this. Adding a pull request makes it easier to comment on the code and submit changes. As mentioned it is easy to fork this repo, push your changes to it and create a pull request. Thanks!

**Comment by ipo** [comment]
I'm not interested in using github that much, sadly.  If you don't want to merge the patch, I understand.

It is for the gwork-branch, I should also mention.

**Comment by billyquith** [comment]
You already have an account with Github. All you have to do is clone this project and push your changes to it. There is no central repo for Git so you can just move the changes around. That is probably easier than creating a diff. 

The advantage of a pull request is that it can be reviewed, and the automated testing will check the code in the PR.

**Comment by eXpl0it3r** [comment]
PR at #43

**Comment by billyquith** [comment]
I'll close this since we have a PR now. Thanks for creating.
