### ISSUE TITLE
How to include it is existing project?

### ISSUE THREAD

**Issue by RUSshy** [billyquith/GWork#46]
Hello

I'm on Windows, and i'm using CLion with MingWin, i'm newbie with CMAKE.. 

I successfully built it, and installed it, i have a folder with the include and the lib, but i now have no idea how to include it in my cmake project xD

Do you mind explaining me please ? thanks :)

Sorry for weird english i'm russian

**Comment by RUSshy** [comment]
I tried this: https://github.com/billyquith/GWork/wiki/Embedding-GWork-in-Cmake-project

But it asked me about renderer, so i manually set it like this:

set(GWK_RENDER_NAME SFML)

And then i get the errors: 

```
CMake Error at game/gwork/source/platform/CMakeLists.txt:40 (add_library):
  Cannot find source file:

    include/Gwork/Renderers/SFML.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at game/gwork/source/samples/CMakeLists.txt:40 (add_executable):
  Cannot find source file:

    SFML/SFMLSample.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "GworkSFML".
CMake Error: CMake can not determine linker language for target: GworkSFML
```

**Comment by RUSshy** [comment]
Oh it was a type error: i had to use SFML2 xD

But there is still an error, in the platform project, for the SFML renderer it doesn't seems to find the SFML headers :/

**Comment by RUSshy** [comment]
Any idea? I tried everything, redownload mingwin sfml clion and gwork, nothing worked

But if i compile an SFML project it works fine, so i'm pretty sure there is an error in the cmake files

**Comment by RUSshy** [comment]
Oh fixed it, i just had to do that:


set(RENDER_SFML2 ON)
add_subdirectory(GWork)

But now i have another issue: undefined reference when calling opengl stuff in the sample project, progress :D

**Comment by RUSshy** [comment]
Got it

I had to add this in the example cmakelist

```make
    # OpenGL
    if(MINGW)
        find_package(OpenGL REQUIRED)
        include_directories(${OPENGL_INCLUDE_DIR})
        if(OPENGL_FOUND)
            message("OpenGL found for MinGW target")
            set(GWK_RENDER_LIBRARIES ${GWK_RENDER_LIBRARIES} ${OPENGL_LIBRARIES})
        else()
            message("Unable to find OpenGL for MinGW target")
        endif()
    endif()
```

**Comment by billyquith** [comment]
> Oh fixed it, i just had to do that:
> `set(RENDER_SFML2 ON)`

Ah, yes, you still have to issue the command-line arguments when generating the file. i.e. see project readme (or docs).

**Comment by billyquith** [comment]
> Cmake is just a pain

Cmake does have kind of a steep learning curve. I didn't like it at first the docs just dump you in at the deep end. That said, if your persevere, it is a very powerful tool, and can often set up a project as fast as you can do it in an IDE. And it will be be cross platform, and work from command-line, IDE.

**Comment by billyquith** [comment]
Thanks for the feedback. I'll see about improving the docs.
