### ISSUE TITLE
MinGW Missing OpenGL library

### ISSUE THREAD

**Issue by RUSshy** [billyquith/GWork#47]
Hello

In order to build and run the Sample project (with SFML renderer, i haven't tested the other ones), you have to add the following entry to the CMakeLists.txt

Otherwise it won't be able to link the opengl libs

```cmake
    # OpenGL
    if(MINGW)
        find_package(OpenGL REQUIRED)
        include_directories(${OPENGL_INCLUDE_DIR})
        if(OPENGL_FOUND)
            message("OpenGL found for MinGW target")
            set(GWK_RENDER_LIBRARIES ${GWK_RENDER_LIBRARIES} ${OPENGL_LIBRARIES})
        else()
            message("Unable to find OpenGL for MinGW target")
        endif()
    endif()
```

**Comment by billyquith** [comment]
Thanks I saw feedback in #46. I'll look into improving the docs. I already added some build info in the doxygen HTML docs. https://billyquith.github.io/GWork/build_gwork.html

**Comment by billyquith** [comment]
Have you tested any other platforms? This is just MinGW? - I think the problem may be related to the SFML [cmake config.](https://github.com/billyquith/GWork/blob/gwork/cmake/Modules/FindSFML.cmake#L318)

```cmake
# update the list
        if(FIND_SFML_OS_WINDOWS)
            set(SFML_WINDOW_DEPENDENCIES ${SFML_WINDOW_DEPENDENCIES} "opengl32" "winmm" "gdi32")
        elseif(FIND_SFML_OS_LINUX)
            set(SFML_WINDOW_DEPENDENCIES ${SFML_WINDOW_DEPENDENCIES} "GL" ${X11_LIBRARY} ${XRANDR_LIBRARY} ${UDEV_LIBRARIES})
        elseif(FIND_SFML_OS_FREEBSD)
            set(SFML_WINDOW_DEPENDENCIES ${SFML_WINDOW_DEPENDENCIES} "GL" ${X11_LIBRARY} ${XRANDR_LIBRARY} "usbhid")
        elseif(FIND_SFML_OS_MACOSX)
            set(SFML_WINDOW_DEPENDENCIES ${SFML_WINDOW_DEPENDENCIES} "-framework OpenGL -framework Foundation -framework AppKit -framework IOKit -framework Carbon")
        endif()
```

[Here are the instructions](http://www.sfml-dev.org/tutorials/2.0/compile-with-cmake.php) for building an SFML app with cmake.

I think the SFML config should find OpenGL, but it doesn't for MinGW. Perhaps you could ask on the SFML forums? I never use MinGW.

**Comment by billyquith** [comment]
Which platform does MinGW report as? If it doesn't report as any of the above ones then GL won't be found.

**Comment by billyquith** [comment]
If you get latest I have put a warning in for when the OS is not recognised and cmake does know where to look for OpenGL.

**Comment by billyquith** [comment]
I'm going to close this as I've made notes in the docs.
