### ISSUE TITLE
CMake fails on Win32 with GLFW

### ISSUE THREAD

**Issue by VirgiliuC** [billyquith/GWork#53]
Hi,

I've been trying to build Gwork using CMake, for Win32 (Windows 7), Code::Blocks with MinGW 5.1.0, using OpenGL renderer with GLFW.
Unfortunately, CMake chokes when finding GLFW, both in command line and GUI mode. Of course, I manually provide the required directory paths (include and lib) for GLFW, but with no success. I attach its log, if of any help:
[CMakeOutput.log.txt](https://github.com/billyquith/GWork/files/1118065/CMakeOutput.log.txt)

_Here is the CMake GUI reported problem:_

> Project version: 0.2.0
> Including tests
> Including sample
> CMake Error at cmake/Modules/FindGLFW.cmake:233 (if):
>   if given arguments:
> 
>     "OR" "OR"
> 
>   Unknown arguments specified
> Call Stack (most recent call first):
>   cmake/Config.cmake:105 (find_package)
>   CMakeLists.txt:29 (include)
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Programming/GWork/build/CMakeFiles/CMakeOutput.log".

Anyway, I tried without any render target (using the Null one), and it succeeds in making the C::B project, but attempting to compile it fails immediately, with this:

> 
> -------------- Clean: all in gwork (compiler: GNU GCC Compiler)---------------
> 
> Cleaned "gwork - all"
> 
> -------------- Build: all in gwork (compiler: GNU GCC Compiler)---------------
> 
> Using makefile: Makefile
> [  1%] Building CXX object source/platform/CMakeFiles/GworkNull.dir/renderers/Null/Null.cpp.obj
> [  2%] Building CXX object source/platform/CMakeFiles/GworkNull.dir/platforms/NullPlatform.cpp.obj
> [  3%] Building CXX object source/platform/CMakeFiles/GworkNull.dir/platforms/PlatformCommon.cpp.obj
> [  4%] Building CXX object source/platform/CMakeFiles/GworkNull.dir/platforms/Utility.cpp.obj
> C:\Programming\GWork\source\platform\platforms\Utility.cpp:26:22: fatal error: iconv.h: No such file or directory
> compilation terminated.
> mingw32-make.exe[2]: *** [source/platform/CMakeFiles/GworkNull.dir/platforms/Utility.cpp.obj] Error 1
> mingw32-make.exe[1]: *** [source/platform/CMakeFiles/GworkNull.dir/all] Error 2
> mingw32-make.exe: *** [all] Error 2
> source\platform\CMakeFiles\GworkNull.dir\build.make:137: recipe for target 'source/platform/CMakeFiles/GworkNull.dir/platforms/Utility.cpp.obj' failed
> CMakeFiles\Makefile2:111: recipe for target 'source/platform/CMakeFiles/GworkNull.dir/all' failed
> Makefile:126: recipe for target 'all' failed
> Process terminated with status 2 (0 minute(s), 4 second(s))
> 4 error(s), 0 warning(s) (0 minute(s), 4 second(s))
>  

Could anyone please help me a bit in this regard?

Many thanks.
Virgiliu

**Comment by billyquith** [comment]
> I manually provide the required directory paths (include and lib) for GLFW

The error message seems to be saying that the version number isn't found in the header.

    parseVersion(GL/glfw.h GLFW_VERSION_MAJOR)

    if(${GLFW_VERSION_MAJOR} OR ${GLFW_VERSION_MINOR} OR ${GLFW_VERSION_REVISION})

Do those defines exist? Perhaps you could put some more debugging messages in the cmake file to see what is happening.

**Comment by billyquith** [comment]
C:\Programming\GWork\source\platform\platforms\Utility.cpp:26:22: fatal error: iconv.h: No such file or directory

Do you have iconv.h installed?

**Comment by VirgiliuC** [comment]
Many thanks for the hints. 
Meanwhile though I managed to build manually the C::B projects, the settings, etc in order to compile  the code (MinGW 5.1.0) and somehow succeeded (after a few mods and harmless amputations :) ). However, I have not been able to run properly a meaningful executable (like Designer), which is odd considering that I built and run successfully the original code GWEN in no time, using its premake4.

Along these lines, may I kindly ask if GWork has ever been used/tested/compiled around the MS Windows platform with OpenGL or even GDI? I tried to build this, but the framework's code is broken both syntactically and conceptually (construction logic). I mean by that: nonexistent named entities, stray inclusions and code blocks, syntax errors and Gwen remnants - for the former, and some non-functional constructions for the latter (like invoking canvas into WindowPlatform - MessagePump, while there is no apparent access of canvas at that functional module's level).

I would truly appreciate some comments (and help/advice) regarding the above. Sorry of not being more specific (I could though give you the exact problems), but this stretches somehow over the whole MSW platform.
Which underlying engine/platform has GWork been used on the most so far?

Thanks again.

**Comment by billyquith** [comment]
> Along these lines, may I kindly ask if GWork has ever been used/tested/compiled around the MS Windows platform with OpenGL or even GDI?

Windows is a bit of a pain for project generators like cmake because of the non-standard install locations. As you can see from the cmake/modules, each module tends to have a different approach. Some not supporting Windows at all, so I guess the necessary variables need to be passed in. I guess at some point I a should add something in the docs about this.

I refactored GWEN to fix some layering issues and switched from Premake to cmake. I work mainly on OSX. I believe the OpenGL/GLFW version of Gwork works. As listed in the readme, only the cross-platform APIs are really tested and working. I don't think it would be much work to get the GDI version working, I just don't have the motivation as I don't need it. Whenever I do stuff I tend to use cross platform APIs. The Windows platform may need some work.

The designer comes from the GWEN project but I suspect is quite broken. I should probably move it into a branch so it is not in the main gwork branch.

**Comment by VirgiliuC** [comment]
Thanks, I thought so. 
I was under the impression though that Designer is developed by you and actively used/maintained, hence my efforts to get it running (could be a useful tool).

Well, I'll do what I can to mend and fix those parts, and if successful I'll let you know, in case of any future interest of updating/expanding things.
I don't use GDI myself, I have always used GLFW with (recently) nanoGUI as GUI, but the latter is incomplete. I just wanted to quickly get something to run on MSW.

I guess I'll try some GWork builds 'by hand'. I assume you don't have any portable means of designing/editing GWork GUI's, do you?

You mentioned the Designer originating from GWEN, but I have no such code in my original gwen download. Would you be so kind to point me where it is? (not only ControlFactory and so).
Thanks.

**Comment by billyquith** [comment]
I fixed the Windows OpenGL build. It does require GLFW. I just use CmakeGUI and point to the paths using that.

> I was under the impression though that Designer is developed by you and actively used/maintained, hence my efforts to get it running (could be a useful tool).

The designer was developed the original author. GWEN now looks abandoned and the designer project has been deleted, so this is the only version of it. It was never complete, just an unfinished experiment by the author.

I started work on a script/data binding to Gwork. You can see work on this in the ponder branch. You can use Lua to create a simple button at the moment. It needs a lot more work! There is no portable GUI designer solution - I think this might be why the author abandoned the designer. He realised it is more work than you think. I would like to have one eventually, but I wanted to automate the load/save using reflection, hence Ponder.

**Comment by VirgiliuC** [comment]
Great, thanks, I'll have a look as soon as I have some time.

But just to clarify: other than designer, GWork is now fully functional on cross-platforms , that is, one can still make an application with it, am I right?

**Comment by billyquith** [comment]
> other than designer, GWork is now fully functional on cross-platforms , that is, one can still make an application with it, am I right?

Yes, have a look at one of the samples, which run the unit tests. They demonstrate all of the controls.

**Comment by VirgiliuC** [comment]
Hi again
Well, I tried it, and although I generated the makefiles and C::B project with CMake, it still needed a hammer, a saw and pliers to get it running :-). It doesn't work out of the box, as the code needs some mods to compile/run under this configuration
Anyway, I can run now the example generated by the CMake. 
However, I tried to create a gwork project as dll. It compiles fine, but the example crashes on the opengl renderer - but this is another story.

PropertyTree class is missing the dll export decoration. The same for OpenGL renderers, if they are to be used from a dll.
MinGW also could not find ::sleep(ms) so I used ::usleep(ms*1000);
Inclusions <GWork/Font.h> and <GWork/Texture.h> do not exists either.
OpenGL_DebugFont c-tor is wrong: it needs a Gwk::Rect as argument to pass on to the underlying constructor. And it does not call the base class OpenGL constructor, which is a must as there's no default c-tor for this one.

And so on. I have other questions for the example that I managed to run, but I'll open a new issue.
Thanks.

**Comment by billyquith** [comment]
> Well, I tried it, and although I generated the makefiles and C::B project with CMake, it still needed a hammer, a saw and pliers to get it running :-). It doesn't work out of the box, as the code needs some mods to compile/run under this configuration

I don't use CodeBlocks or MinGW. I don't really know about their config. If you have you fixes for the cmake config files then please create a branch, fix, and submit a PR. 

> PropertyTree class is missing the dll export decoration. The same for OpenGL renderers, if they are to be used from a dll.

If you find new issues could you either create a new issue, or submit a PR. Thanks.

The is a free, open source project. If you'd like to help fix it then be my guest. I'm very busy at the moment so none of this will get fixed any time soon. Regards.
