### ISSUE TITLE
Gwork SDL2 Sample issues(screen is broken)

### ISSUE THREAD

**Issue by wwforever** [billyquith/GWork#59]
I have built and run the GWork SDL2 sample, but the screen is broken like a snapshot. What have I missed? Is there a solution?

![gwork_sdl2_sample](https://user-images.githubusercontent.com/6159154/28853738-9d2550ce-776d-11e7-8339-b87c3366bf14.png)

**Comment by wwforever** [comment]
The dll file associated with sdl2_image was copied and the texture was successfully loaded. But the controls do not look right.
![gwork_sdl2_sample2](https://user-images.githubusercontent.com/6159154/28857640-e7f2acb0-7785-11e7-9abc-345e4146980f.png)

**Comment by billyquith** [comment]
> The dll file associated with sdl2_image was copied and the texture was successfully loaded.

The first image looks like it didn't find the skin texture, so I think think the default colour is red.

> But the controls do not look right.

Second image shows a (potential) scissoring/clipping bug in SDL2. See #18.

If you have the latest SDL2 and latest Gwork (gwork branch) then this should be fixed and you should no longer see this problem.

**Comment by wwforever** [comment]
@billyquith Thank you for answer. I am using the latest SDL2 (2.0.5) and the latest GWork. I'll check it again.

**Comment by wwforever** [comment]
```
void SDL2::StartClip()
{
    return; //not clip
    const Gwk::Rect &rect = ClipRegion();

    int w, h;
    SDL_GetRendererOutputSize(SDL_GetRenderer(m_window), &w, &h);

    // Something wrong with clip rectangles in SDL2?
    // https://bugzilla.libsdl.org/show_bug.cgi?id=2700
    // =>   clip.y = screenHieght - clip.y - clip.h;
    const SDL_Rect clip = { rect.x, h - rect.y - rect.h, rect.w, rect.h };

    SDL_RenderSetClipRect(m_renderer, &clip);
}

void SDL2::EndClip()
{
    return; //not clip
    SDL_RenderSetClipRect(m_renderer, 0);
}
```

The source of the GWork I am using is the latest version. After temporarily blocking the clip processing by processing the return from StartClip and EndClip, I have confirmed that it works almost as close to normal. However, you can see that clipping is not working properly.

![gwork_sdl2_clip_return](https://user-images.githubusercontent.com/6159154/28900120-d2067d7e-7829-11e7-9515-f4ffa764eb76.png)

**Comment by wwforever** [comment]
```
void SDL2::StartClip()
{
	const Gwk::Rect &rect = ClipRegion();
	const SDL_Rect clip = { rect.x, rect.y, rect.w,rect.h };
    //const Gwk::Rect &rect = ClipRegion();

    //int w, h;
    //SDL_GetRendererOutputSize(SDL_GetRenderer(m_window), &w, &h);

    //// Something wrong with clip rectangles in SDL2?
    //// https://bugzilla.libsdl.org/show_bug.cgi?id=2700
    //// =>   clip.y = screenHieght - clip.y - clip.h;
    //const SDL_Rect clip = { rect.x, h - rect.y - rect.h, rect.w, rect.h };

    SDL_RenderSetClipRect(m_renderer, &clip);
}
```
I went back to the previous revision of the issue [#18](https://github.com/billyquith/GWork/issues/18) and found that it works fine. It seems to have fixed a bug related to SDL_RenderSetClipRect in the latest version of SDL2 2.0.5.

![gwork_sdl2_clip_ok](https://user-images.githubusercontent.com/6159154/28902485-1214a624-783a-11e7-918e-e42e554c8271.png)

**Comment by billyquith** [comment]
Thanks for reporting this. It does indeed appear to not happen any more. I put in a test for versions of SDL2 pre 2.0.5.
