### ISSUE TITLE
TTF_Quit();  crash  fix in SDL2Sample.cpp

### ISSUE THREAD

**Issue by elix22** [billyquith/GWork#62]
Nice work on the SDL port .
Anyway to fix this crash  just add  **skin.ReleaseFont(skin.GetDefaultFont());**👍 
`
    SDL_DestroyWindow(window);
    SDL_Quit();
    skin.ReleaseFont(skin.GetDefaultFont());
    TTF_Quit();  
`

One more thing 
In windows "DefaultSkin.png"  and "OpenSans.ttf" will  fail to load
The following will fix it 👍 
`
#ifdef _WINDOWS
#include <windows.h> 
#endif

...
...
#ifdef _WINDOWS
	char * dir = SDL_GetBasePath();
	SetCurrentDirectory(dir);
#endif

`

**Comment by billyquith** [comment]
Thanks for the fixes. I put the font clean up one in.

I'd like to put cross-platform fixes in for the resource path. I had similar problems with SFML2. I don't have a Windows setup to test this on at the moment.

**Comment by billyquith** [comment]
Closing. Mentioned in #66
