### ISSUE TITLE
Blank Renderer

### ISSUE THREAD

**Issue by kklouzal** [billyquith/GWork#67]
Please consider adding a 'blank' renderer for users to begin work on creating their own custom renderers.
Thank you for your time and hard work!

**Comment by eXpl0it3r** [comment]
There's a null renderer, what do you understand with a "blank" renderer?

**Comment by billyquith** [comment]
> Please consider adding a 'blank' renderer for users to begin work on creating their own custom renderers.

If you look at the [base class for the renderers](https://github.com/billyquith/GWork/blob/gwork/source/platform/include/Gwork/BaseRender.h) there are various comments on how to implement one. 

There are also samples. It is easy enough to work out what you need. Perhaps look at one of the similar renderers (SDL, Allegro5, or software/SW) for an example. The DirectX ones have a lot of noise in them. 

I'll try and add some more notes to the docs.

**Comment by kklouzal** [comment]
Thank you, I copied the Allegro Renderer structure, its a slight barrier to get started developing, especially on windows using visual studio, when you need cmake to generate project files. Some documentation about Renderer, Input, Platform and a quick overview of what needs to be done in the cmake scripts to generate your project files would do wonders!

**Comment by billyquith** [comment]
I added [an introduction](https://billyquith.github.io/GWork/intro_gwork.html).  There are already some notes on using cmake in the [build docs](https://billyquith.github.io/GWork/build_gwork.html).
