### ISSUE TITLE
"LARGE_INTEGER" and "QueryPerformanceCounter" problem

### ISSUE THREAD

**Issue by Liu-shua** [billyquith/GWork#75]
Issue:

- Operating System (name & version):
windows 7 X86_64，I use msys2 (Unix like sys)
- Compiler (name & version):
Gcc 7.3.0 
- Target renderer:
SDL2
- cmake command-line used:
cmake -G "MSYS Makefiles" -DRENDER_SDL2=ON ..

![qq 20180506164231](https://user-images.githubusercontent.com/25896518/39671534-9980e28a-514c-11e8-9be3-6c842618d25a.jpg)

**Comment by billyquith** [comment]
I guess you need to change the define to include Windows headers for MSYS
https://github.com/billyquith/GWork/blob/gwork/source/platform/platforms/CrossPlatform.cpp#L14

Which defines does it need?

**Comment by billyquith** [comment]
I believe this is fixed with 9ceada8909854d39971ee71b493bd467fb1dfe31
