### ISSUE TITLE
Can't build OpenGL sample with MinGW

### ISSUE THREAD

**Issue by Megaxela** [billyquith/GWork#76]
Issue:

- Operating System (name & version): Windows 10 Professional
- Compiler (name & version): mingw-w64 7.3.0
- Target renderer: OpenGL (Crossplatform)
- cmake command-line used: cmake -DRENDER_OPENGL=On -DGLFW_LIBRARIES=path_to_libglfw3.a -DGLFW_INCLUDE_DIR=path_to_include .

First of all, `CrossPlatform.cpp` does not includes `Windows.h`, because mingw does not set `_MSC_VER` define. 
Whole block from 14 to 22 line can be changed on the following, I guess:
```cpp
#ifdef WIN32
#    include <Windows.h>
#    include <WinBase.h>
#else
#    include <unistd.h>
#endif
#ifdef _MSC_VER
#   define WIN32_LEAN_AND_MEAN
#   undef min
#   undef max
#endif
```

In the second place: When linking OpenGL sample there is an error: 
`localcharset.c:(.text+0xa): undefined reference to `__imp_GetACP'`
That can be fixed by adding `iconv` to linker (-liconv).

**Comment by billyquith** [comment]
Thanks for the tips! 👍  I'll fix later.
