### ISSUE TITLE
Can't use GWork as cmake `subdirectory`.

### ISSUE THREAD

**Issue by Megaxela** [billyquith/GWork#77]
Issue:

- Operating System (name & version): Windows 10 Professional
- Compiler (name & version): mingw32-w64 7.3.0
- Target renderer: OpenGL
- cmake command-line used: cmake -DRENDER_OPENGL=On -DGLFW_LIBRARIES=path_to_libglfw3.a -DGLFW_INCLUDE_DIR=path_to_include .

When adding GWork as subdirectory (cmake's `add_subdirectory`), include directories are not appended to target's. To fix this, instead of using `include_directories` it will be more useful to use `target_include_directories(Gwork PUBLIC place_include_directories_here)`.

**Comment by billyquith** [comment]
Ok, will look into this.
