### ISSUE TITLE
SFML2 Compile fails - Linux Mint 18.3

### ISSUE THREAD

**Issue by WatIsDeze** [billyquith/GWork#90]
Linux Mint 18.3

Although this is a minor bug, and I'm not very fond of forking, I did figure I'd make note of it and provide the solution in here as well. 

When compiling there is an error related to the \ being used in the preprocessor that should not be there. Simply removing all the \\ and keeping the code in 1 single line resolved the problem.

`#if defined(__unix__) || defined(__linux__) || defined(__gnu__linux__) || (defined (__APPLE__) && defined(__MACH__))
#include <unistd.h>
#endif`

Hope to have been of any use. Because, although this project's git page states it does a successful Linux build, it does not state with which renderer it was being built.

**Comment by billyquith** [comment]
Ah, it's because there are two! `\\` - fixed.

**Comment by billyquith** [comment]
The CI test only builds the null renderer. Otherwise I'd have to set up the CI environment for each renderer.
